### ISSUE TITLE
Does no longuer build.. does not find "meta-yocto"

### ISSUE THREAD

**Issue by antibarbie** [calaos/calaos-os#13]
(23 mars 2016) Current version _b00c10b_ does not compiles. Build machine on a fresh _Ubuntu 15.10 (GNU/Linux 4.2.0-35-generic x86_64)_ as recommended on the calaos forum.

Bitbake fails searching files in a meta-yocto (and meta-yocto-bsp) directory
which does not exists.. 

> 
IOError: [Errno 2] file /home/anti/bitbake/calaos/src/meta-yocto/meta-yocto-bsp/conf/layer.conf not found
ERROR: Unable to parse /home/anti/bitbake/calaos/src/meta-yocto/meta-yocto-bsp/conf/layer.conf

I'm lost, I'm not familiar at all with yocto. Maybe a layer is missing ?
If I manually hack a new layer entry for head revision in the meta-yocto git
repository, the ./build.sh init/update create some interesting directory structures,
but the some awk scripts seems to fail... :-( and then bitbake fails with "recipe not found"

Please help, it looks like a familiar it-builds-on-my-computer problem :-(

FYI: Commit f1508ab would fail during "build init" : 
> 
Permission denied (publickey).
fatal: Could not read from remote repository.

and Commit 302a28e seems ok.

**Comment by raoulh** [comment]
Should be fixed now
