### ISSUE TITLE
Usb serial modules are missing, among others probably (commit 302a28e)

### ISSUE THREAD

**Issue by antibarbie** [calaos/calaos-os#14]
I was worried that mysensors would not run anymore, (no /dev/ttyUSB0) but in fact, the modules usbserial and ch341 in my particular case were simply missing.

Well, I could not spot exactly were the regression went from, but it feels like a major bug.

> lsmod
> Module                  Size  Used by
> ipv6                  365835  34

BTW It worked ok on commit 6e79f41

> $ lsmod
> Module                  Size  Used by
> 8021q                  20959  0
> garp                    7318  1 8021q
> stp                     2102  1 garp
> llc                     5782  2 stp,garp
> ch341                   6289  0
> usbserial              31089  1 ch341
> bcm2835_gpiomem         3627  0
> uio_pdrv_genirq         3685  0
> uio                    10236  1 uio_pdrv_genirq
> sch_fq_codel            8486  2
> ipv6                  365835  34

**Comment by raoulh** [comment]
For which MACHINE are you building?

**Comment by antibarbie** [comment]
I am building for raspberrypi
      (./build.sh init raspberrypi)
      
      BTW I was unable to test with the last commit -- still for
      raspberrypi -- (qt fails to compile, maybe a missing dependancy ?)
      
       
    
    
      For which MACHINE are you building?
      —
        You are receiving this because you authored the thread.
        Reply to this email directly or view
          it on GitHub

**Comment by antibarbie** [comment]
This is no longer the case in Calaos-3-alpha6
